/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenta.autotechtalleres.vistas.talleres;

import davidpuertocuenta.autotechtalleres.clases.Talleres;
import davidpuertocuenta.autotechtalleres.controladores.TallerControlador;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author David Puerto Cuenca
 */
public class VistaCitasTaller extends javax.swing.JFrame {
    private Talleres taller;
    private TallerControlador controlador = new TallerControlador();
    /**
     * Creates new form VistaCitasTaller
     */
    public VistaCitasTaller() {
        initComponents();
        this.setLocationRelativeTo(null);
        controlador.crearTablaCitasTaller(tablaCitasTaller, this.taller);
        desplegableCitas.setVisible(false);
        
        //Listeners para la funcion despegable de citas en MenuBar.
        MouseAdapter mostrarOcultarDesplegable = new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                desplegableCitas.setVisible(true);
            }

            @Override
            public void mouseExited(MouseEvent e) {
         desplegableCitas.setVisible(false);
            }
        };

        botonCitas.addMouseListener(mostrarOcultarDesplegable);
        botonCambiarEstado.addMouseListener(mostrarOcultarDesplegable);
        botonEliminarCita.addMouseListener(mostrarOcultarDesplegable);
    }
    
    public VistaCitasTaller(Talleres taller) {
        initComponents();
        this.taller = taller;
        this.setLocationRelativeTo(null);
        controlador.crearTablaCitasTaller(tablaCitasTaller, this.taller);
        desplegableCitas.setVisible(false);
        
        //Listeners para la funcion despegable de citas en MenuBar.
        MouseAdapter mostrarOcultarDesplegable = new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                desplegableCitas.setVisible(true);
            }

            @Override
            public void mouseExited(MouseEvent e) {
         desplegableCitas.setVisible(false);
            }
        };

        botonCitas.addMouseListener(mostrarOcultarDesplegable);
        botonCambiarEstado.addMouseListener(mostrarOcultarDesplegable);
        botonEliminarCita.addMouseListener(mostrarOcultarDesplegable);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desplegableCitas = new javax.swing.JPanel();
        botonCambiarEstado = new javax.swing.JButton();
        botonEliminarCita = new javax.swing.JButton();
        organizadorVistaPrincipal = new javax.swing.JPanel();
        botonRefrescar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitasTaller = new javax.swing.JTable();
        labelCitasDelVehiculo = new javax.swing.JLabel();
        CabeceraVehiculos = new javax.swing.JLabel();
        MenuBarPersonalizada = new javax.swing.JPanel();
        botonCitas = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autotech - Talleres");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desplegableCitas.setBackground(new java.awt.Color(0, 0, 0));
        desplegableCitas.setLayout(null);

        botonCambiarEstado.setBackground(new java.awt.Color(0, 0, 0));
        botonCambiarEstado.setForeground(new java.awt.Color(255, 255, 255));
        botonCambiarEstado.setText("   Cambiar Estado");
        botonCambiarEstado.setToolTipText("");
        botonCambiarEstado.setBorder(null);
        botonCambiarEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonCambiarEstado.setMaximumSize(new java.awt.Dimension(100, 30));
        botonCambiarEstado.setPreferredSize(new java.awt.Dimension(100, 30));
        botonCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarEstadoActionPerformed(evt);
            }
        });
        desplegableCitas.add(botonCambiarEstado);
        botonCambiarEstado.setBounds(0, 0, 100, 30);

        botonEliminarCita.setBackground(new java.awt.Color(0, 0, 0));
        botonEliminarCita.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarCita.setText("   Eliminar Cita");
        botonEliminarCita.setToolTipText("");
        botonEliminarCita.setBorder(null);
        botonEliminarCita.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonEliminarCita.setMaximumSize(new java.awt.Dimension(100, 30));
        botonEliminarCita.setPreferredSize(new java.awt.Dimension(100, 30));
        botonEliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarCitaActionPerformed(evt);
            }
        });
        desplegableCitas.add(botonEliminarCita);
        botonEliminarCita.setBounds(0, 30, 100, 30);

        getContentPane().add(desplegableCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 100, 60));

        organizadorVistaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        organizadorVistaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        organizadorVistaPrincipal.setLayout(null);

        botonRefrescar.setBackground(new java.awt.Color(255, 255, 255));
        botonRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icono_actualizar.png"))); // NOI18N
        botonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarActionPerformed(evt);
            }
        });
        organizadorVistaPrincipal.add(botonRefrescar);
        botonRefrescar.setBounds(1190, 70, 60, 40);

        tablaCitasTaller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero De Cita", "Fecha", "Matricula", "Estado De Cita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCitasTaller);

        organizadorVistaPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 1250, 560);

        labelCitasDelVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelCitasDelVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        labelCitasDelVehiculo.setText("Citas Del Taller");
        organizadorVistaPrincipal.add(labelCitasDelVehiculo);
        labelCitasDelVehiculo.setBounds(20, 60, 520, 60);

        CabeceraVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/cabecera_vehiculos_prov.jpg"))); // NOI18N
        organizadorVistaPrincipal.add(CabeceraVehiculos);
        CabeceraVehiculos.setBounds(10, 60, 1250, 66);

        MenuBarPersonalizada.setBackground(new java.awt.Color(0, 0, 0));
        MenuBarPersonalizada.setMaximumSize(new java.awt.Dimension(1920, 20));
        MenuBarPersonalizada.setMinimumSize(new java.awt.Dimension(200, 20));
        MenuBarPersonalizada.setName(""); // NOI18N
        MenuBarPersonalizada.setLayout(null);

        botonCitas.setBackground(new java.awt.Color(0, 0, 0));
        botonCitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonCitas.setForeground(new java.awt.Color(255, 255, 255));
        botonCitas.setText("Citas");
        botonCitas.setBorder(null);
        botonCitas.setFocusPainted(false);
        botonCitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCitas.setMaximumSize(new java.awt.Dimension(200, 100));
        botonCitas.setPreferredSize(new java.awt.Dimension(100, 50));
        MenuBarPersonalizada.add(botonCitas);
        botonCitas.setBounds(0, 0, 100, 50);

        botonCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        botonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarSesion.setText("Cerrar Sesión");
        botonCerrarSesion.setBorder(null);
        botonCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCerrarSesion.setMaximumSize(new java.awt.Dimension(200, 100));
        botonCerrarSesion.setPreferredSize(new java.awt.Dimension(100, 50));
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });
        MenuBarPersonalizada.add(botonCerrarSesion);
        botonCerrarSesion.setBounds(1170, 0, 100, 50);

        organizadorVistaPrincipal.add(MenuBarPersonalizada);
        MenuBarPersonalizada.setBounds(0, 0, 1280, 50);

        getContentPane().add(organizadorVistaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        controlador.cerrarSesion(this);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonEliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarCitaActionPerformed
        controlador.eliminarCita(tablaCitasTaller, this, taller);
    }//GEN-LAST:event_botonEliminarCitaActionPerformed

    private void botonCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarEstadoActionPerformed
        controlador.vistaDialogCamiarEstado(this, tablaCitasTaller);
            controlador.crearTablaCitasTaller(tablaCitasTaller, this.taller);
    }//GEN-LAST:event_botonCambiarEstadoActionPerformed

    private void botonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarActionPerformed
        controlador.crearTablaCitasTaller(tablaCitasTaller, this.taller);
    }//GEN-LAST:event_botonRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCitasTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCitasTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCitasTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCitasTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCitasTaller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CabeceraVehiculos;
    private javax.swing.JPanel MenuBarPersonalizada;
    private javax.swing.JButton botonCambiarEstado;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonCitas;
    private javax.swing.JButton botonEliminarCita;
    private javax.swing.JButton botonRefrescar;
    private javax.swing.JPanel desplegableCitas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCitasDelVehiculo;
    private javax.swing.JPanel organizadorVistaPrincipal;
    private javax.swing.JTable tablaCitasTaller;
    // End of variables declaration//GEN-END:variables
}
