/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenta.autotechtalleres.vistas.talleres;

import davidpuertocuenta.autotechtalleres.clases.Talleres;
import davidpuertocuenta.autotechtalleres.controladores.TallerControlador;

/**
 *
 * @author David Puerto Cuenca
 */
public class VistaCitasTaller extends javax.swing.JFrame {
    private Talleres taller;
    private TallerControlador controlador = new TallerControlador();
    /**
     * Creates new form VistaCitasTaller
     */
    public VistaCitasTaller() {
        initComponents();
        setExtendedState(VistaCitasTaller.MAXIMIZED_BOTH);
        controlador.crearTablaCitasTaller(tablaCitasTaller, this.taller);
        controlador.colocarCerrarSesion(jMenuBar1, jMenu5); 
    }
    
    public VistaCitasTaller(Talleres taller) {
        initComponents();
        setExtendedState(VistaCitasTaller.MAXIMIZED_BOTH);
        this.taller = taller;
        controlador.crearTablaCitasTaller(tablaCitasTaller, this.taller);
        controlador.colocarCerrarSesion(jMenuBar1, jMenu5); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitasTaller = new javax.swing.JTable();
        labelCitasDelVehiculo = new javax.swing.JLabel();
        CabeceraVehiculos = new javax.swing.JLabel();
        fondoPantalla = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        JMenuItemCancelarCita = new javax.swing.JMenuItem();
        Vehículos = new javax.swing.JMenu();
        JMenuItemVehículos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tablaCitasTaller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero De Cita", "Fecha", "Matricula", "Estado De Cita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCitasTaller);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 1900, 940);

        labelCitasDelVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelCitasDelVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        labelCitasDelVehiculo.setText("Citas Del Taller");
        getContentPane().add(labelCitasDelVehiculo);
        labelCitasDelVehiculo.setBounds(30, 0, 510, 80);

        CabeceraVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/cliente/cabecera_vehiculos_prov.jpg"))); // NOI18N
        getContentPane().add(CabeceraVehiculos);
        CabeceraVehiculos.setBounds(20, 10, 1900, 66);

        fondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_vistaGeneral_prov.jpg"))); // NOI18N
        getContentPane().add(fondoPantalla);
        fondoPantalla.setBounds(0, 0, 1920, 1030);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(90, 32768));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuClientes.setForeground(new java.awt.Color(255, 255, 255));
        jMenuClientes.setText("Citas");
        jMenuClientes.setToolTipText("");
        jMenuClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuClientes.setMinimumSize(new java.awt.Dimension(50, 22));
        jMenuClientes.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemCancelarCita.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemCancelarCita.setText("Cancelar");
        JMenuItemCancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCancelarCitaActionPerformed(evt);
            }
        });
        jMenuClientes.add(JMenuItemCancelarCita);

        jMenuBar1.add(jMenuClientes);

        Vehículos.setForeground(new java.awt.Color(255, 255, 255));
        Vehículos.setText("Vehículos");
        Vehículos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Vehículos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vehículos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Vehículos.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemVehículos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemVehículos.setText("Mis Vehículos");
        JMenuItemVehículos.setToolTipText("");
        JMenuItemVehículos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemVehículosActionPerformed(evt);
            }
        });
        Vehículos.add(JMenuItemVehículos);

        jMenuBar1.add(Vehículos);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Cerrar Sesión");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItemCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCancelarCitaActionPerformed
      //  controlador.cancelarCitas(tablaCitasVehiculo, vehiculo, this);
    }//GEN-LAST:event_JMenuItemCancelarCitaActionPerformed

    private void JMenuItemVehículosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemVehículosActionPerformed
       // controlador.vistaVehiculos(this, cliente);
    }//GEN-LAST:event_JMenuItemVehículosActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
       // controlador.cerrarSesion(this);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCitasTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCitasTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCitasTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCitasTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCitasTaller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CabeceraVehiculos;
    private javax.swing.JMenuItem JMenuItemCancelarCita;
    private javax.swing.JMenuItem JMenuItemVehículos;
    private javax.swing.JMenu Vehículos;
    private javax.swing.JLabel fondoPantalla;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCitasDelVehiculo;
    private javax.swing.JTable tablaCitasTaller;
    // End of variables declaration//GEN-END:variables
}
