/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenta.autotechtalleres.vistas.login;

import davidpuertocuenta.autotechtalleres.controladores.LoginControlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;


/**
 *
 * @author David Puerto Cuenca
 */
public class LoginTalleres extends javax.swing.JFrame {
    private LoginControlador controlador = new LoginControlador();
    /**
     * Creates new form TestLogin
     */
    public LoginTalleres() {
        initComponents();

        //Método para acceder al programa pulsando enter.
        textContrasena.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               controlador.iniciarSesionUsuarios(textUsuario.getText(), textContrasena.getPassword(), LoginTalleres.this); 
            }
        });
        
        //Método para acceder al programa pulsando enter.
        textUsuario.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              controlador.iniciarSesionUsuarios(textUsuario.getText(), textContrasena.getPassword(), LoginTalleres.this);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioLogin = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        botonMostrarContrasena = new javax.swing.JToggleButton();
        textUsuario = new javax.swing.JTextField();
        botonIniciarSesion = new javax.swing.JToggleButton();
        botonRegistro = new javax.swing.JButton();
        textContrasena = new javax.swing.JPasswordField();
        labelContrasena = new javax.swing.JLabel();
        labelRegistro = new javax.swing.JLabel();
        labelIniciarSesion = new javax.swing.JLabel();
        labelUsuario1 = new javax.swing.JLabel();
        fondoCabecera = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JLabel();
        fondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formularioLogin.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/logo_prov.jpg"))); // NOI18N
        formularioLogin.add(logo);
        logo.setBounds(120, 30, 100, 99);

        botonMostrarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMostrarContrasena.png"))); // NOI18N
        botonMostrarContrasena.setBorder(null);
        botonMostrarContrasena.setContentAreaFilled(false);
        botonMostrarContrasena.setFocusPainted(false);
        botonMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarContrasenaActionPerformed(evt);
            }
        });
        formularioLogin.add(botonMostrarContrasena);
        botonMostrarContrasena.setBounds(270, 300, 40, 40);
        formularioLogin.add(textUsuario);
        textUsuario.setBounds(90, 230, 218, 42);

        botonIniciarSesion.setText("Login");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        formularioLogin.add(botonIniciarSesion);
        botonIniciarSesion.setBounds(140, 360, 110, 40);

        botonRegistro.setText("Crear cuenta");
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        formularioLogin.add(botonRegistro);
        botonRegistro.setBounds(230, 410, 100, 30);
        formularioLogin.add(textContrasena);
        textContrasena.setBounds(90, 300, 218, 42);

        labelContrasena.setBackground(new java.awt.Color(255, 255, 255));
        labelContrasena.setForeground(new java.awt.Color(255, 255, 255));
        labelContrasena.setText("Contraseña");
        formularioLogin.add(labelContrasena);
        labelContrasena.setBounds(90, 280, 80, 16);

        labelRegistro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistro.setText("¿No tienes cuenta?");
        formularioLogin.add(labelRegistro);
        labelRegistro.setBounds(80, 410, 140, 30);

        labelIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        labelIniciarSesion.setText("Iniciar Sesión");
        formularioLogin.add(labelIniciarSesion);
        labelIniciarSesion.setBounds(110, 140, 150, 40);

        labelUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        labelUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario1.setText("Usuario");
        formularioLogin.add(labelUsuario1);
        labelUsuario1.setBounds(90, 210, 60, 16);

        fondoCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/cabecera_prov.png"))); // NOI18N
        formularioLogin.add(fondoCabecera);
        fondoCabecera.setBounds(70, 140, 225, 50);

        fondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_login_prov .jpg"))); // NOI18N
        formularioLogin.add(fondoLogin);
        fondoLogin.setBounds(0, 0, 410, 490);

        getContentPane().add(formularioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 410, 490));

        fondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_prov.jpg"))); // NOI18N
        getContentPane().add(fondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarContrasenaActionPerformed
        if (textContrasena.getEchoChar() == '\u0000') {
            textContrasena.setEchoChar('•');
            botonMostrarContrasena.setIcon(new ImageIcon(getClass().getResource("/icons/IconMostrarContrasena.png")));
        } else {
            textContrasena.setEchoChar('\u0000');
            botonMostrarContrasena.setIcon(new ImageIcon(getClass().getResource("/icons/IconOcultarContrasena.png")));
        }
    }//GEN-LAST:event_botonMostrarContrasenaActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        controlador.iniciarSesionUsuarios(textUsuario.getText(), textContrasena.getPassword(), this);
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        controlador.vistaRegistroUsuarios(this);
    }//GEN-LAST:event_botonRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTalleres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTalleres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTalleres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTalleres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTalleres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonIniciarSesion;
    private javax.swing.JToggleButton botonMostrarContrasena;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JLabel fondoCabecera;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JLabel fondoPantalla;
    private javax.swing.JPanel formularioLogin;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelIniciarSesion;
    private javax.swing.JLabel labelRegistro;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField textContrasena;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
