/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenta.autotechtalleres.vistas.login;

import davidpuertocuenta.autotechtalleres.controladores.LoginControlador;
import static davidpuertocuenta.autotechtalleres.util.Estilos.aplicarEstiloBoton;
import static davidpuertocuenta.autotechtalleres.util.Estilos.aplicarEstiloPasswordField;
import static davidpuertocuenta.autotechtalleres.util.Estilos.aplicarEstiloTextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;


/**
 *
 * @author David Puerto Cuenca
 */
public class LoginTalleres extends javax.swing.JFrame {
    private LoginControlador controlador = new LoginControlador();
    /**
     * Creates new form TestLogin
     */
    public LoginTalleres() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Estilos FrontEnd
        aplicarEstiloBoton(botonIniciarSesion);
        aplicarEstiloBoton(botonRegistro);
        aplicarEstiloTextField(textUsuario);
        aplicarEstiloPasswordField(textContrasena);
                
        //Método para acceder al programa pulsando enter.
        textContrasena.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               controlador.iniciarSesionUsuarios(textUsuario.getText(), textContrasena.getPassword(), LoginTalleres.this); 
            }
        });
        
        //Método para acceder al programa pulsando enter.
        textUsuario.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              controlador.iniciarSesionUsuarios(textUsuario.getText(), textContrasena.getPassword(), LoginTalleres.this);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioLogin = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        botonMostrarContrasena = new javax.swing.JToggleButton();
        textUsuario = new javax.swing.JTextField();
        botonRegistro = new javax.swing.JButton();
        textContrasena = new javax.swing.JPasswordField();
        labelContrasena = new javax.swing.JLabel();
        labelRegistro = new javax.swing.JLabel();
        labelIniciarSesion = new javax.swing.JLabel();
        labelUsuario1 = new javax.swing.JLabel();
        botonIniciarSesion = new javax.swing.JButton();
        fondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autotech - Talleres");
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formularioLogin.setToolTipText("");
        formularioLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/logo.png"))); // NOI18N
        formularioLogin.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        botonMostrarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/IconMostrarContrasena.png"))); // NOI18N
        botonMostrarContrasena.setBorder(null);
        botonMostrarContrasena.setContentAreaFilled(false);
        botonMostrarContrasena.setFocusPainted(false);
        botonMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarContrasenaActionPerformed(evt);
            }
        });
        formularioLogin.add(botonMostrarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 40, 40));
        formularioLogin.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 218, 42));

        botonRegistro.setText("Crear cuenta");
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        formularioLogin.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 120, 30));
        formularioLogin.add(textContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 218, 42));

        labelContrasena.setBackground(new java.awt.Color(255, 255, 255));
        labelContrasena.setForeground(new java.awt.Color(255, 255, 255));
        labelContrasena.setText("Contraseña");
        formularioLogin.add(labelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, -1));

        labelRegistro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistro.setText("¿No tienes cuenta?");
        formularioLogin.add(labelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, 30));

        labelIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        labelIniciarSesion.setText("Iniciar Sesión");
        formularioLogin.add(labelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, 40));

        labelUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        labelUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario1.setText("Usuario");
        formularioLogin.add(labelUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 60, -1));

        botonIniciarSesion.setText("Login");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        formularioLogin.add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, 30));

        getContentPane().add(formularioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 410, 450));
        formularioLogin.setBackground(new java.awt.Color(0, 0, 0, 120));

        fondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_login.jpg"))); // NOI18N
        getContentPane().add(fondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        controlador.vistaRegistroUsuarios(this);
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void botonMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarContrasenaActionPerformed
        if (textContrasena.getEchoChar() == '\u0000') {
            textContrasena.setEchoChar('•');
            botonMostrarContrasena.setIcon(new ImageIcon(getClass().getResource("/icons/IconMostrarContrasena.png")));
        } else {
            textContrasena.setEchoChar('\u0000');
            botonMostrarContrasena.setIcon(new ImageIcon(getClass().getResource("/icons/IconOcultarContrasena.png")));
        }
    }//GEN-LAST:event_botonMostrarContrasenaActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
         controlador.iniciarSesionUsuarios(textUsuario.getText(), textContrasena.getPassword(), LoginTalleres.this);
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTalleres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTalleres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTalleres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTalleres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTalleres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JToggleButton botonMostrarContrasena;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JLabel fondoPantalla;
    private javax.swing.JPanel formularioLogin;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelIniciarSesion;
    private javax.swing.JLabel labelRegistro;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField textContrasena;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
